### ISSUE TITLE
Add the Spring 2019 cohort section to the Graduates page #63 

### ISSUE THREAD

**Issue by selamcoding** [team-refcode/refcode.org#76] opened 2019-07-12 03:06 UTC
Hey team i only added my link for today. I will be working may be tomorrow.
![DSC_0088](https://user-images.githubusercontent.com/47615618/61099544-b5faaa80-a430-11e9-8783-0b0b26a4db4a.jpg)

**Comment by brentonstrine** [comment] 2019-07-13 19:30
I am closing this as @MustafaAlsaeedi pointed out that it is a duplicate of #63

**Closed by brentonstrine** 2019-07-13 19:30 UTC
